- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: pods
  kindname: Pod
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: configmaps
  kindname: ConfigMap
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: secrets
  kindname: Secret
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: services
  kindname: Service
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: persistentvolumeclaims
  kindname: PersistentVolumeClaim
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: persistentvolumes
  kindname: PersistentVolume
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: daemonsets
  kindname: DaemonSet
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: deployments
  kindname: Deployment
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: replicasets
  kindname: ReplicaSet
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: statefulsets
  kindname: StatefulSet
- apigroup: workload.caicloud.io
  apiversion: v1alpha1
  pkgpath: github.com/caicloud/clientset/pkg/apis/workload/v1alpha1
  pkgname: wklv1a1
  resourcename: workloads
  kindname: Workload
  iscrd: true
