- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: pods
  kindname: Pod
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: configmap
  kindname: ConfigMap
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: secret
  kindname: Secret
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: persistentvolumeclaim
  kindname: PersistentVolumeClaim
- apigroup: core
  apiversion: v1
  pkgpath: k8s.io/api/core/v1
  pkgname: corev1
  resourcename: persistentvolume
  kindname: PersistentVolume
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: daemonset
  kindname: DaemonSet
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: deployment
  kindname: Deployment
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: replicaset
  kindname: ReplicaSet
- apigroup: apps
  apiversion: v1
  pkgpath: k8s.io/api/apps/v1
  pkgname: appsv1
  resourcename: statefulset
  kindname: StatefulSet
