apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admission
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zxq-app: admission-test
  name: admission-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      zxq-app: admission-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        zxq-app: admission-test
    spec:
      containers:
      - name: admission
        env:
        - name: SERVER_SERVICE_NAMESPACE
          value: "default"
        - name: SERVER_SERVICE_NAME
          value: "admission-test"
        - name: SERVER_SERVICE_SELECTOR
          value: "zxq-app:admission-test"
        image: cargo.dev.caicloud.xyz/release/kube-admission-test-server:dc356da-dirty
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: admission
